server:
    port: 8182

spring:
    application:
        name: xxl-job-admin
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    datasource:
        name: test
        url: jdbc:mysql://172.17.13.13:3306/xxl-job?useUnicode=true&characterEncoding=UTF-8&useSSL=true
        username: xxl
        password: xxl123
        # druid
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    ## Freemarker 配置
    freemarker:
      template-loader-path: classpath:/templates
      cache: true
      charset: utf-8
      content-type: text/html
      suffix: .ftl
      expose-spring-macro-helpers: true
      expose-request-attributes: true
      expose-session-attributes: true
      request-context-attribute: request
      check-template-location: true
      settings:
          template_update_delay: 0
          default_encoding: UTF-8
          output_encoding: UTF-8
          locale: zh_CN
          number_format: 0.##########
          date_format: yyyy-MM-dd
          time_format: HH:mm:ss
          datetime_format: yyyy-MM-dd HH:mm:s
          classic_compatible: true
          template_exception_handler: ignore

mybatis:
    basepackage: com.xxl.job.admin.mapper
    xmlLocation: classpath:mapper/**/*.xml
quartz:
    configLocation: quartz.properties

